version: '3.8'

services:
    db:
        image: mysql:8.0
        container_name: mysql
        restart: always
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        volumes:
            - dbdata:/var/lib/mysql
        ports:
            - "3306:3306"

volumes:
    dbdata:
