version: '3.8'

services:
    app:
        build: .
        container_name: laravel-app
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - "8000:8000"
        depends_on:
            - db
        networks:
            - laravel
        command: php artisan serve --host=0.0.0.0 --port=8000

    db:
        image: mysql:8.0
        container_name: mysql
        restart: always
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        volumes:
            - dbdata:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - laravel

volumes:
    dbdata:

networks:
    laravel:
